### ISSUE TITLE
Retrieving formants time series

### ISSUE THREAD

**Issue by hadware** [YannickJadoul/Parselmouth#12]
Hello, 

I'd like to retrieve the 3 first formants array for a `Sound` object. I came up with this code:
```python3
formants = snd.to_formant_burg()
formants_ts = {}
timestep = formants.get_time_step()
for formant_idx in range(1,4):
    formants_ts[formant_idx] = np.array([formants.get_value_at_time(formant_idx, i * timestep) 
                              for i in range(0, formants.get_number_of_frames())])
```
It seems to work fine, but is there any cleaner way to do that using your API (especially considering the fact that when the formants are written to text, it's obvious it must be cleanly stored somewhere).

**Comment by YannickJadoul** [comment]
Hi @hadware, as you have probably [noticed in the documentation ](https://parselmouth.readthedocs.io/en/latest/api_reference.html#parselmouth.Formant), the Python interface of `Formant` is quite limited.

Technically, this is partly because Praat's `Formant` class does not inherit `Matrix` and so the `values` property does not exist for `Formant`, for example, because these values are not stored in the same way as a `Sound`'s or 'Intensity`'s values. However, there is no reason why this API isn't more complete (like `Pitch`, for example), except for a lack of time.

I've been trying to finish some things for a 0.4.0 release, so I'll try to add this to that release as well. So thanks for bringing this to my attention again! :-)

Meanwhile, your solution is the closest you can get, without using `parselmouth.praat.call`. A slightly shorter (and maybe faster?) solution might be the following, though, using Praat's `Hack > To Matrix...` command:

```python
formants_ts[formant_idx] = parselmouth.praat.call(formants, "To Matrix", formant_idx).values[0,:]
```

**Comment by YannickJadoul** [comment]
Any help extending the API (whether it's designing the API or also implementing it) is of course welcome, if you want to have this faster and are up for a challenge ;-)

**Comment by hadware** [comment]
Thanks for your answer (and your marvelous work, this truly is a great project!).
Speed isn't much of a concern for my current usage of parselmouth, but your ´To Matrix´ hack seems to be the best way to do that.

I don't have much time, and I'm not entirely sure how to contribute to parselmouth, but i'd really like to. I've extensively used TextGrids (using basically all the other TextGrid manipulation libraries available in python, and let me tell you, they _suck_), and the the voice features extraction functions (such as the ones used [here](https://github.com/drfeinberg/PraatScripts/blob/master/Measure%20Pitch%2C%20HNR%2C%20Jitter%2C%20and%20Shimmer.ipynbl) (sorry you have to see this code, it really is a pitiful sight)). I could also help "pythonizing" the higher-level wrappers. Or just plain ol' issue reportin' on every little detail that bugged me.

**Comment by YannickJadoul** [comment]
Thanks :-)
The beauty/horrifying reality of Python is that you can of course also force things like this, if you want to keep your algorithm itself cleaner:
```python
parselmouth.Formant.get_values = lambda self, i: parselmouth.praat.call(self, "To Matrix", i).values[0, :]
```

Anyway, I was not trying to force you into contributing, but just mentioning that if you are interested, anything (corrections to the documentation, extra examples, a critique of the Python API, ...) is highly motivating and appreciated :-) So if you are, feel free to join the (very inactive) [Gitter development chatbox](https://gitter.im/PraatParselmouth/Development); but no pressure, there.

(By the way, 0.4.0 will also contain an interface between `parselmouth.TextGrid` and [TextGridTool](https://github.com/hbuschme/TextGridTools)'s TextGrid: https://parselmouth.readthedocs.io/en/latest/api_reference.html#parselmouth.TextGrid)

**Comment by hadware** [comment]
No worries I'm actually willing to help, no worries! You single handedly allowed my project to advance very must faster than we expected it to. I'll look up the Gitter chatbox.
