### ISSUE TITLE
Feature Extraction?

### ISSUE THREAD

**Issue by hunaa** [YannickJadoul/Parselmouth#2]
Can Parselmouth be used for pitch tracking and MFCC feature extraction from audio?

**Comment by YannickJadoul** [comment]
@hunaa Yes, you are probably looking for `parselmouth.Sound.to_mfcc` and `parselmouth.Sound.to_pitch`.
Also have a look at [the API reference in the documentation](https://parselmouth.readthedocs.io/en/latest/api_reference.html) and [the examples](https://parselmouth.readthedocs.io/en/latest/examples.html).

**Comment by hunaa** [comment]
Any code for this specific question? I want to extract pitch from all wave files in the directory and save the values in a csv file.

**Comment by YannickJadoul** [comment]
What do you mean? The example that comes closest is probably https://parselmouth.readthedocs.io/en/latest/examples/batch_processing.html, but every use case is slightly different, so in this case you'll have to replace the bit where the harmonicity is extracted by something where you extract pitch (using `to_pitch` on your sound object). Moreover, the pitch will vary within audio fragments, so I'm not sure how you're going to save one value per audio file?

PS: There is a Gitter chat, where it will be easier to ask small questions back and forth, instead of a GitHub issue: https://gitter.im/PraatParselmouth/Lobby

**Comment by hunaa** [comment]
Thanks for sharing the chat link, I'll ask there now.

**Comment by YannickJadoul** [comment]
Sure, please do!
