### ISSUE TITLE
Trouble getting PointProcess from sound with Parselmouth

### ISSUE THREAD

**Issue by calebstrait** [YannickJadoul/Parselmouth#20]
I'm trying to use Parselmouth to calculate jitter from a .wav file, but PointProcess is giving me trouble.

Following [this](https://github.com/drfeinberg/PraatScripts/blob/master/Measure%20Pitch%2C%20HNR%2C%20Jitter%2C%20Shimmer%2C%20and%20Formants.ipynb), I do
```
sound = parselmouth.Sound(path) # path = path to .wav
pointProcess = parselmouth.praat.call(sound, "To PointProcess (periodic, cc)")
```
intending to follow up with
```
jitter = parselmouth.praat.call(pointProcess, "Get jitter (local)", 0, 0, 0.0001, 0.02, 1.3)
```
but before I can, I get this error:
```
Command "To PointProcess (periodic, cc)" not available for given objects
```
Any clue what I'm doing wrong?

**Comment by YannickJadoul** [comment]
@calebstrait Yes, I think I know: the actual Praat action is `"To PointProcess (periodic, cc)..."` rather than `"To PointProcess (periodic, cc)"`, because it takes arguments and would open a form in the Praat GUI.

When you add arguments to an action, Parselmouth will try to be nice and add `"..."` to the end of the action name, if it's not there (similar to what happens in Praat scripts). So either writing `parselmouth.praat.call(sound, "To PointProcess (periodic, cc)...")` or `parselmouth.praat.call(sound, "To PointProcess (periodic, cc)", "BLAH")` should result in a more useful error (something about the number or types of arguments you're passing), but you're case is a bit unlucky, where you have neither. (I agree it's a bit annoying but because of the way Praat's internals are structured, it's extremely hard or impossible without major hacks to get the number and type of arguments an action expects :-( )

Does that work for you?

**Comment by Zacarias153** [comment]
did you manage to find the f0mim and f0max?

**Comment by YannickJadoul** [comment]
@aarushiksk, I described the solution in this comment, just above: https://github.com/YannickJadoul/Parselmouth/issues/20#issuecomment-545635071
If you need more than that, you'll have to be more precise than this about your problem, and perhaps ask a new question on Gitter or in a new issue.

**Comment by wetdog** [comment]
I could extract jitter with this code 
```
pointProcess = parselmouth.praat.call(sound, "To PointProcess (periodic, cc)", 75, 600)
jitter = parselmouth.praat.call(pointProcess, "Get jitter (local)", 0, 0, 0.0001, 0.02, 1.3)
```
