### ISSUE TITLE
Change pitch and formant with praat-parselmouth

### ISSUE THREAD

**Issue by qo4on** [YannickJadoul/Parselmouth#25]
Is it possible? I didn't find this in documentation.

**Comment by YannickJadoul** [comment]
There is an example in the docs ["Pitch manipulation and Praat commands"](https://parselmouth.readthedocs.io/en/latest/examples/pitch_manipulation.html) that shows you how to manipulate the pitch of an audio fragment.

For formants, I don't know. Parselmouth is based on Praat; did you look at the Praat documentation if there is a way to do so? If you know how to do it in Praat, it should be straightforward to do it with Parselmouth and I'm happy to help, but I'm not an expert on everything Praat has to offer.

**Comment by YannickJadoul** [comment]
I did a quick search and found a page in the documentation of Praat saying "The manipulation of formant contours cannot be as straightforward as the manipulation of pitch, duration, or intensity contours." (see http://www.fon.hum.uva.nl/praat/manual/Intro_8_4__Manipulation_of_formants.html).

But I also found this one: http://www.praatvocaltoolkit.com/change-formants.html. So maybe it is possible in some way? Have a look around if you can achieve what you want in Praat. If so, `parselmouth.praat.call` and/or `parselmouth.praat.run` can help you do this in Python with Parselmouth.

**Comment by qo4on** [comment]
Thank you! I have never worked with `praat` before, so it's difficult to find right info. `praat-parselmouth` says:
```
manipulation = call(sound, "To Manipulation", 0.001, 75, 600)
```
Praat docs shows time step 10 times bigger value than `praat-parselmouth`. Which one is better? And how should I choose min and max?
```
timeStep
the time step (or frame length) used in the pitch analysis. A common value is 0.010 seconds.
minimumPitch
the minimum pitch frequency considered in the pitch analysis. A common value is 75 hertz.
maximumPitch
the maximum pitch frequency considered in the pitch analysis. A common value is 600 hertz.
```
I found a [video](https://youtu.be/LPSVs-ecNI4?t=75) which shows how to use formants in `praat`. How can I draw the same mel with red formant dots?

**Comment by drfeinberg** [comment]
I have a Jupyter Notebook with full instructions on how to manipulate pitch and formants in parselmouth here: https://github.com/drfeinberg/Parselmouth-Guides/tree/master/ManipulatingVoices.ipynb

**Comment by YannickJadoul** [comment]
@qo4on 

> Thank you! I have never worked with `praat` before, so it's difficult to find right info. `praat-parselmouth` says:
> 
> ```
> manipulation = call(sound, "To Manipulation", 0.001, 75, 600)
> ```
> 
> Praat docs shows time step 10 times bigger value than `praat-parselmouth`. Which one is better? And how should I choose min and max?
>
> ```
> timeStep
> the time step (or frame length) used in the pitch analysis. A common value is 0.010 seconds.
> minimumPitch
> the minimum pitch frequency considered in the pitch analysis. A common value is 75 hertz.
> maximumPitch
> the maximum pitch frequency considered in the pitch analysis. A common value is 600 hertz.
> ```
> 

I don't know which one is better, but I definitely meant to use Praat's default value there. So thanks for noticing! I pushed a commit to fix it! :-)

On choosing parameters: in general, I'm not an expert on all the analysis algorithms implemented in Praat, so I don't know the details of the trade-offs behind choosing the parameters (Parselmouth mainly provides the Python interface to the already existing/implemented Praat algorithms), so it's often good to refer to the Praat docs: http://www.fon.hum.uva.nl/praat/manual/Manipulation.html.

However, in this case, I do actually know some things about the pitch-estimation algorithm, and if I recall correctly, it is based on fixed window sliding over the audio fragment:
- The step size determines how much the sliding window moves every time, so many pitch estimates will be taken. I would assume a too small step size would mainly result in the algorithm being slower (i.e., 0.001 takes 10 times more samples than 0.01). A too large step size would result in loss of resolution of the estimated pitch curve, then.
- The minimum pitch determines how big the sliding window will be. If the minimum pitch is too high, low pitches will not have enough periods within a single window frame, and won't be detected correctly.
- The maximum frequency is mostly used to exclude impossible pitch values and make sure the fundamental frequency is detected rather than an accidentally strong harmonic.

In general, Praat's default values should be a good starting position for human speech data, so unless you have reason to believe your data has different characteristics and you want to tweak the parameters (maybe interactively, in Praat's user interface?), I'd keep those.

For more details, I'd suggest digging into the Praat docs or Paul Boersma's article on the pitch analysis algorithm that Praat uses: http://www.fon.hum.uva.nl/paul/papers/Proceedings_1993.pdf

> I found a [video](https://youtu.be/LPSVs-ecNI4?t=75) which shows how to use formants in `praat`. How can I draw the same mel with red formant dots?

This is showing the formants, I think. Not manipulating them. There's `parselmouth.Sound.to_formant` that does a formant analysis. From there, you should be able to extract the values (`get_value_at_time`, with an optional `unit` parameter) such that you can later plot them with whichever plotting library you prefer.

> I installed the toolkit from your link. It seems it works. Do you know how can I run `Change formants` script?

You can use `parselmouth.praat.run` or `parselmouth.praat.run_file` to run an existing Praat script. I thought there was an example in the docs, but apparently I still haven't fully written it down :-(
Anyway, the unreleased docs explain `run` and `run_file`: https://parselmouth.readthedocs.io/en/latest/api_reference.html#parselmouth.praat.run_file (just be aware that some keyword arguments like `extra_objects` or `keep_cwd` are not yet in the latest release 0.3.0).

**Comment by YannickJadoul** [comment]
> I have a Jupyter Notebook with full instructions on how to manipulate pitch and formants in parselmouth here: https://github.com/drfeinberg/Parselmouth-Guides/tree/master/ManipulatingVoices.ipynb

@drfeinberg Thanks! That's also quite interesting, with some extra explanation of what's happening :-)
I haven't look at how the praatvocaltoolkit.com script works, but it seems it allows to change the formants independently from each other and is more complex, but also more powerful than yours?

**Comment by qo4on** [comment]
@YannickJadoul Thanks a lot.
@drfeinberg Your tutorial is amazing, thank you. Fix a few mistakes there in the last 2 cells:
```
Audio(data=manipulated_sound.values, rate=**resampled_sound**.sampling_frequency)
```

**Comment by drfeinberg** [comment]
Thanks. I'll fix that up.

**Comment by drfeinberg** [comment]
Yes the Praat toolkit can change individual formants. I haven't used it myself in research because i've not been happy with the sound quality.

**Comment by YannickJadoul** [comment]
@drfeinberg Aha, good to know and have the alternative for changing them all by the same factor, then! (I know I still need to add your repository to the docs. Still on my backlog, sorry.)

@qo4on I'm assuming this more or less solves the question, so I'll close this issue? Feel free to reopen if necessary (or drop by the [Gitter](https://gitter.im/PraatParselmouth/Lobby) if you have some more/other small questions. It's often easier to have a quick conversation there!)
