### ISSUE TITLE
Remove noise with Parselmouth

### ISSUE THREAD

**Issue by qo4on** [YannickJadoul/Parselmouth#26]
I found that Praat can do [some noise reduction](http://www.fon.hum.uva.nl/praat/manual/Sound__Remove_noise___.html). But it filters out a range of frequncies and does not take a sample of noise.
Do you know how I can remove noise from audio based on the sample of noise with Parselmouth?

**Comment by drammock** [comment]
The praat function you linked to *does* base its noise reduction on a sample of noise. That's what the `noise time range` parameter selects. And the bandpass filtering is under user control too.

**Comment by qo4on** [comment]
The problem is that I don't know the location of the noise without signal in audio files. It differs from file to file. I have a file with just noise and I'd like to use it for all the files.

**Comment by YannickJadoul** [comment]
I don't think there's a [Python API](https://parselmouth.readthedocs.io/en/latest/api_reference.html) for this yet (not sure why; I thought the `Sound` interface was pretty complete), but just like in #25, you can access Praat functionality through `parselmouth.praat.call`. So, something like `parselmouth.praat.call(sound, "Remove noise", 0.0, 0.0, 0.025, 80.0, 10000.0, 40.0, "Spectral subtraction")` should work. These are Praat's default parameters, so you might want to change them.

Apart from that, as @drammock mentions (thanks, @drammock!), the Praat functionality is indeed documented on the Praat web page you link to. I don't really know more about the internals of this function, but that seems to be a nice explanation? There's also some explanation on how Praat can automatically guess where the noise is. Otherwise, you could probably concatenate a fragment of noise to the front/back, use it in this function, and remove it later.

I'm going to close this as not really being a Parselmouth issue, but more related to standard Praat functionality and usage. Feel free to more informally discuss or bounce ideas on [Gitter](https://gitter.im/PraatParselmouth/Lobby), though.

**Comment by talvelumi** [comment]
The `parselmouth.praat.call` implementation of "remove noise" takes 7 arguments, while the Praat script version (v6.1.38) takes 8. The noise reduction parameter is unreachable in parselmouth, and the result seem to differ. Why is that?

**Comment by YannickJadoul** [comment]
Hi, @talvelumi! I think this might be due to the confusion between "Remove noise" and "Reduce noise".

If you see, there are two separate functions in Praat. "Remove noise" has 7 arguments, and "Reduce noise" has 8:
https://github.com/YannickJadoul/Parselmouth/blob/stable/praat/dwtools/praat_David_init.cpp#L5901-L5932

But confusingly, "Remove noise" is hidden by default in the GUI, and you can only see the similarly named "Reduce noise":
https://github.com/YannickJadoul/Parselmouth/blob/stable/praat/dwtools/praat_David_init.cpp#L8908-L8909

If you want to see the difference, you can show the button via the "Praat > Preferences > Buttons..." menu:
![image](https://github.com/YannickJadoul/Parselmouth/assets/8025744/9636db1c-2099-461d-8c3c-8c603ef3318a)

**Comment by YannickJadoul** [comment]
Do let me know if I overlooked something.

On top of this, I believe I've ran into a bug in Praat 6.1.38 for this function, so beware of this. I'm currently actively working towards a new version of Parselmouth with an updated version of Praat (which does not have this bug), aiming to release Parselmouth 0.5.0 around the time Python 3.12 gets released.

Meanwhile, you could use a development version, if you urgently need to use this: Find the latest run of the "Wheels" action on `master` (https://github.com/YannickJadoul/Parselmouth/actions/workflows/wheels.yml?query=branch%3Amaster), and download the wheels artifact: 
![image](https://github.com/YannickJadoul/Parselmouth/assets/8025744/0060cc05-1ec1-451e-bfc9-b2c9e0bb8dda)
In here, you will find different pre-compiled packages, of which you can select the version that matches your Python version and OS.

If you need any further help, don't hesitate to contact me, either here, by email, or [on Gitter](https://gitter.im/PraatParselmouth/Lobby).

**Comment by john-veillette** [comment]
Just gonna leave this here in case it saves anyone else a headache...

The following won't work (with parselmouth v0.4.3 at least):
```
sound = call(sound, 'Remove noise...', 0., 0., 0.025, 80.0, 10000.0, 40.0, 'Spectral subtraction')
```
Instead, you need
```
sound = call(sound, 'Remove noise...', 0., 0., 0.025, 80.0, 10000.0, 40.0,  'spectral-subtraction')
```
Uppercase+space "Spectral subtraction" is what I've seen used in regular praat script, so I'm guessing this has something to do with enum conversion, since the noise reduction argument seems to be an enum in the .cpp backend. But I haven't played around with the praat source code (or pybind, for that matter) enough to be certain.

**Comment by YannickJadoul** [comment]
@john-veillette, thanks for leaving a note on this! I had a closer look into this.

However, I can't get the first version (using "Spectral subtraction") to work in Praat itself (Praat version 6.3.15):
![image](https://github.com/YannickJadoul/Parselmouth/assets/8025744/38653909-8ccb-4f06-ad60-04e8617e4f7a)

Could you elaborate or give an example of a Praat script with this working? What version of Praat are you using?

Maybe they changed something over the years, in different Praat versions? But at least in this version, I can't get it to work with anything else than what it shows in the GUI form:
![image](https://github.com/YannickJadoul/Parselmouth/assets/8025744/eee7d930-ef73-4601-aed7-5cd59613164e)

**Comment by YannickJadoul** [comment]
Alright, I dug a bit deeper into Praat, and it would seem that this changed somewhere in 2019: https://github.com/praat/praat/commit/53c06e37f51850d8918fea70a65874a9747d7484#diff-9844b9c358338662ee7ad70aa14ab00df36b7d7c9a914bbc7f8d6dd9300aef66

At this point, they swapped out the list of values to use this enum: https://github.com/praat/praat/blob/53c06e37f51850d8918fea70a65874a9747d7484/dwtools/Sound_extensions_enums.h

Could it be that you were using a version of Praat older than 6.0.50 (i.e., from before March 28, 2019)? If so, this should be the reason, Praat having changed this, and Parselmouth 0.4.3 using/depending on a newer Praat 6.1.38 internally.

If not, I'm still very curious to hear more, and resolve this discrepancy!

**Comment by john-veillette** [comment]
Hi Yannick, thanks for the reply. When I say I've seen "Spectral subtraction" used in a praat script, I do mean I've _seen_ it (e.g. in this [stackexchange thread](https://linguistics.stackexchange.com/questions/20118/how-to-apply-remove-noise-filter-in-praat-script), which is indeed from six years ago so checks out with your explanation). I personally interface with praat almost exlusively through parselmouth :) so I haven't run the function directly in praat myself.

I don't think this is really a dependency issue that needs to be managed, just a weird gap in the praat documentation (which still features a screenshot of the GUI using the old "Spectral subtraction" rather than "spectral-subtraction"). But the parselmouth call interface is working as expected, nothing to worry about.
