### ISSUE TITLE
Save as spreadsheet file?

### ISSUE THREAD

**Issue by nullpunktTUD** [YannickJadoul/Parselmouth#27]
Thanks for this awesome project! 

Have I missed a way to save an object as a spreadsheet (like the Praat menu entry Save->Save as PitchTier spreadsheet file)? If not, are there any plans to add that function?

**Comment by YannickJadoul** [comment]
@nullpunktTUD Thanks! :-)

All Praat actions can be accessed through `parselmouth.praat.call`, also the ones in the menu. As far as I know that's already the only way to get a `PitchTier` for the moment, or did you find another way?
I just tried, and this works for me:

```pycon
>>> import parselmouth
>>> sound = parselmouth.Sound("the_north_wind_and_the_sun.wav")
>>> pitch_tier = parselmouth.praat.call(sound.to_pitch(), "Down to PitchTier")
>>> parselmouth.praat.call(pitch_tier, "Save as PitchTier spreadsheet file", "the_north_wind_and_the_sun.PitchTier")
```

There's no nicer Python API for this, for the moment, but for saving `Sound` and generic `Data` object, there is: [`parselmouth.Sound.save`](https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Sound.save), [`parselmouth.Data.save`](https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Data.save), [`parselmouth.Data.save_as_binary_file`](https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Data.save_as_binary_file), etc. (All objects in the object list are `Data` in Praat, so these three default "Save as ..." entries in the Praat menu are available as methods for all Parselmouth objects.)

Apart from that, "are there any plans to add that function?". Yes, there's always lots of plans, but never enough time ;-) :-(
There's a plan in the back of my mind to allow Praat `Table`s to be converted to Pandas `DataFrame`s, but someone would need to help out or magically need to provide me with some time (or even better, take over my other work!) to get me started on that.

That being said: "just" adding a Python class API for a class like `PitchTier` (instead of `parselmouth.praat.call`) shouldn't take ages, so with a bit of help and motivation, that's always a possibility.

**Comment by nullpunktTUD** [comment]
Wow, the generic ```praat.call()``` way to do it was almost too obvious. Worked like a charm!

I would love to help out creating a proper ```PitchTier``` API with the little time I have to spare. It would all basically just be wrappers around the corresponding ```praat.call()``` calls, right? 

I have never actually collaborated on GitHub, though. Should I just give it a shot and then send you the code to review?

**Comment by YannickJadoul** [comment]
> Wow, the generic `praat.call()` way to do it was almost too obvious. Worked like a charm!

Ha, good to hear! :-)

> I would love to help out creating a proper `PitchTier` API with the little time I have to spare. It would all basically just be wrappers around the corresponding `praat.call()` calls, right?
> 
> I have never actually collaborated on GitHub, though. Should I just give it a shot and then send you the code to review?

I was about to point you to Gitter, but seems you have already found it :-) Unfortunately, the Python API is created on the C++ side, for better performance and nicer errors etc, so it's slightly more complex than wrappers around `praat.call`.
