### ISSUE TITLE
Play and Annotation？

### ISSUE THREAD

**Issue by RayOsLei** [YannickJadoul/Parselmouth#3]
Can Parselmouth be used for play  and annotation from audio?
@YannickJadoul

**Comment by RayOsLei** [comment]
@YannickJadoul

**Comment by YannickJadoul** [comment]
Playing is currently not supported, since that imposes extra dependencies on external libraries and since the focus of Parselmouth is on exposing the acoustic algorithms and functionality for Python scripts. However, you can access the wave data (`Sound.values`) and the sampling frequency (`Sound.sampling_frequency`), so you can use existing Python libraries to play sound (e.g., simpleaudio, http://simpleaudio.readthedocs.io/en/latest/, or PyAudio, https://people.csail.mit.edu/hubert/pyaudio/; or see the list at https://wiki.python.org/moin/Audio/).

And I don't understand what you mean with "annotation". Do you mean interactively annotating an audio file? Just use Praat for such interactive use; I don't see why you'd do that in Python. If you mean accessing TextGrids, have a look at [the examples in the documentation](http://parselmouth.readthedocs.io/en/latest/examples.html): [one of the examples there](http://parselmouth.readthedocs.io/en/latest/examples/pitch_manipulation.html) show how you can access most Praat commands.

**Comment by RayOsLei** [comment]
thanks @YannickJadoul
