### ISSUE TITLE
parselmouth.PraatError: Not an audio file.

### ISSUE THREAD

**Issue by hackedbyxx** [YannickJadoul/Parselmouth#96]
```python
sound = parselmouth.Sound(tmp.name)
parselmouth.PraatError: Not an audio file.
```
some .m4a audio file can play normaly,but can't read from parselmouth directly, it must be converted to get correct sound

**Comment by YannickJadoul** [comment]
Can it be read by Praat itself? If not, that's why.

If that's the issue, you can read read in the audio file with some other Python library (I've used [`SoundFile`](https://pysoundfile.readthedocs.io/en/latest/) in the past), convert the values to floats between -1 and 1 (if `SoundFile` reads integer values), and construct a `parselmouth.Sound` object with those.

**Comment by YannickJadoul** [comment]
See e.g. here: https://groups.google.com/g/parselmouth/c/l9pzddg7xZI

**Comment by hackedbyxx** [comment]
> See e.g. here: https://groups.google.com/g/parselmouth/c/l9pzddg7xZI

thanks, i've tried it,but it seems not useful than pydub's AudioSegment, and i try catch exception,so when parselmouth cant's read the file i convert it, but unfortunally it's depency on ffmpeg
